# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('slug', models.SlugField()),
                ('img', models.ImageField(upload_to='projects')),
                ('size', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
    ]
