# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='square',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tech',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
