# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0002_auto_20170115_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.IntegerField(),
        ),
    ]
