# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0003_auto_20170115_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='media/projects'),
        ),
    ]
