# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0005_auto_20170115_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Статьи',
                'verbose_name': 'Статья',
            },
        ),
        migrations.CreateModel(
            name='Techno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemo', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Технологии',
                'verbose_name': 'Технология',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='price',
        ),
        migrations.RemoveField(
            model_name='project',
            name='square',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech',
        ),
        migrations.AddField(
            model_name='article',
            name='techs',
            field=models.ManyToManyField(to='dvor.Techno'),
        ),
        migrations.AddField(
            model_name='project',
            name='techs',
            field=models.ManyToManyField(to='dvor.Techno'),
        ),
    ]
