# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0007_auto_20170120_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrjPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'Вид'), (2, 'План 1 этажа'), (3, 'План 2 этажа')])),
                ('img', sorl.thumbnail.fields.ImageField(upload_to='projects')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=sorl.thumbnail.fields.ImageField(upload_to='projects'),
        ),
        migrations.AddField(
            model_name='prjphoto',
            name='prn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Photos', to='dvor.Project'),
        ),
    ]
