# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0009_auto_20170121_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='square',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
