# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0011_auto_20170123_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='techno',
            name='main',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
    ]
