# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0012_techno_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='techno',
            name='show_in_menu',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
    ]
