# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0013_techno_show_in_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=80)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.CharField(max_length=400)),
                ('file', models.FileField(blank=True, null=True, upload_to='calc_files')),
                ('kit_numb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dvor.PrjKit')),
            ],
        ),
    ]
