# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0014_calculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=80)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('wtime', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Звонки',
                'verbose_name': 'Обратный звонок',
            },
        ),
        migrations.AlterModelOptions(
            name='calculation',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
