# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0015_auto_20170202_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecall',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
