# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 08:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0016_auto_20170202_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='metadesc',
            field=models.CharField(blank=True, max_length=250, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='metakey',
            field=models.CharField(blank=True, max_length=250, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок в браузере'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(verbose_name='Урл'),
        ),
    ]
