# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 05:04
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0018_project_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='prjkit',
            name='kit3',
            field=ckeditor.fields.RichTextField(default='3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prjkit',
            name='price3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
