# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0019_auto_20170224_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readyobj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemo', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=240, unique=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('img', sorl.thumbnail.fields.ImageField(upload_to='readyobj')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvor.Techno')),
            ],
            options={
                'verbose_name_plural': 'Готовые объекты',
                'verbose_name': 'Готовый объект',
            },
        ),
        migrations.CreateModel(
            name='ReadyPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveSmallIntegerField()),
                ('img', sorl.thumbnail.fields.ImageField(upload_to='readyobj')),
                ('prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dvor.Readyobj')),
            ],
            options={
                'verbose_name_plural': 'Фото объекта',
                'verbose_name': 'Фото объекта',
            },
        ),
    ]
