# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0020_readyobj_readyphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemo', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=240, unique=True)),
                ('slug', models.SlugField()),
                ('sort_re', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Реконструкция',
                'verbose_name_plural': 'Реконструкции',
            },
        ),
        migrations.CreateModel(
            name='ReconstPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveSmallIntegerField()),
                ('img', sorl.thumbnail.fields.ImageField(upload_to='reconstr')),
                ('prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dvor.Reconst')),
            ],
            options={
                'verbose_name': 'Фото реконструкции',
                'verbose_name_plural': 'Фото реконструкции',
            },
        ),
    ]
