# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0022_reconst_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название отзыва')),
                ('slug', models.SlugField(verbose_name='Урл')),
                ('owner', models.CharField(max_length=100, unique=True, verbose_name='Владелец')),
                ('owner_img', sorl.thumbnail.fields.ImageField(upload_to='Reviews', verbose_name='Фото владельца')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('sort_re', models.PositiveSmallIntegerField(verbose_name='Сортировка')),
                ('review_img', sorl.thumbnail.fields.ImageField(upload_to='Reviews', verbose_name='Фото (скриншот) отзыва')),
                ('review_text', models.TextField(verbose_name='Текст отзыва')),
                ('house_img', sorl.thumbnail.fields.ImageField(upload_to='Reviews', verbose_name='Фото дома')),
                ('house_desc', models.TextField(verbose_name='Описание дома')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dvor.Project', verbose_name='По какому проекту')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvor.Techno')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
                'verbose_name': 'Отзыв',
            },
        ),
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveSmallIntegerField()),
                ('img', sorl.thumbnail.fields.ImageField(upload_to='Reviews')),
                ('prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dvor.Review')),
            ],
            options={
                'verbose_name_plural': 'Фото дома для отзыва',
                'verbose_name': 'Фото дома для отзыва',
            },
        ),
    ]
