# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 16:38
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0023_review_reviewphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='house_img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='Reviews', verbose_name='Фото дома'),
        ),
        migrations.AlterField(
            model_name='review',
            name='owner_img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='Reviews', verbose_name='Фото владельца'),
        ),
    ]
