# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0024_auto_20170303_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='house_img',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='Reviews', verbose_name='Фото дома'),
        ),
        migrations.AlterField(
            model_name='review',
            name='owner_img',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='Reviews', verbose_name='Фото владельца'),
        ),
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dvor.Project', verbose_name='По какому проекту'),
        ),
    ]
