# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0025_auto_20170303_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='note',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='review',
            name='house_img',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='reviews', verbose_name='Фото дома'),
        ),
        migrations.AlterField(
            model_name='review',
            name='owner_img',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='reviews', verbose_name='Фото владельца'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_img',
            field=sorl.thumbnail.fields.ImageField(upload_to='reviews', verbose_name='Фото (скриншот) отзыва'),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='img',
            field=sorl.thumbnail.fields.ImageField(upload_to='reviews'),
        ),
    ]
