# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0026_auto_20170321_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='readyobj',
            name='sort_re',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
