# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dvor', '0027_readyobj_sort_re'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrjBuilt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', sorl.thumbnail.fields.ImageField(upload_to='projects')),
                ('prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builts', to='dvor.Project')),
            ],
            options={
                'verbose_name_plural': 'Построенные дома',
                'verbose_name': 'Построенный дом',
            },
        ),
    ]
